/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.illinois.starts.gradle.plugin;

import edu.illinois.starts.gradle.plugin.tasks.StartsHelp;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class StartsPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().create(StartsHelp.NAME, StartsHelp.class);
    }
}
