/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.illinois.starts.gradle.plugin;

import edu.illinois.starts.gradle.plugin.tasks.CleanTask;
import edu.illinois.starts.gradle.plugin.tasks.HelpTask;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class StartsPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getTasks().create(HelpTask.NAME, HelpTask.class);
        project.getTasks().create(CleanTask.NAME, CleanTask.class);
    }
}
