/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.illinois.starts.gradle.plugin;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'edu.illinois.starts.plugin.gradle' plugin.
 */
class StartsPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("edu.illinois.starts");

        // Verify the result
        assertNotNull(project.getTasks().findByName("startsHelp"));
        assertNotNull(project.getTasks().findByName("startsClean"));
        assertNotNull(project.getTasks().findByName("startsDiff"));
        assertNotNull(project.getTasks().findByName("startsRun"));
    }
}
